"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Engagement } from "@/types/engagement";
import { CompanyDiagnostic } from "@/types/diagnostic";
import { getEngagement, saveEngagement } from "@/lib/storage/engagements";
import {
  generateAIDiagnostic,
  generateRefinedDiagnostic,
} from "@/lib/ai/diagnostic-generator";
import { DiagnosticOverview } from "@/components/diagnostic/DiagnosticOverview";
import { Button } from "@/components/ui/button";
import { Loader2, RefreshCw, Sparkles, ChevronDown, ChevronUp, Info, ArrowRight } from "lucide-react";
import Link from "next/link";

interface HypothesisPageClientProps {
  engagementId: string;
}

/**
 * Check whether the diagnostic is stale — i.e., maturity ratings
 * have been added or changed since the diagnostic was generated.
 */
function isDiagnosticStale(engagement: Engagement): boolean {
  const diagnostic = engagement.diagnostic;
  if (!diagnostic?.generatedAt) return false;

  const generatedAt = new Date(diagnostic.generatedAt).getTime();

  const hasRatings = engagement.processAssessments.some(
    (pa) => pa.maturityRatings && Object.keys(pa.maturityRatings).length > 0
  );

  if (!hasRatings) return false;

  const updatedAt = new Date(engagement.updatedAt).getTime();
  return updatedAt > generatedAt;
}

/**
 * Compute delta summary between previous and current diagnostics.
 */
interface DiagnosticDelta {
  aiApplicabilityShifts: {
    bucket: string;
    oldRange: string;
    newRange: string;
  }[];
  opportunityShifts: {
    metric: string;
    oldRange: string;
    newRange: string;
  }[];
}

function computeDelta(
  previous: CompanyDiagnostic,
  current: CompanyDiagnostic
): DiagnosticDelta | null {
  const aiShifts: DiagnosticDelta["aiApplicabilityShifts"] = [];
  const oppShifts: DiagnosticDelta["opportunityShifts"] = [];

  const buckets = [
    { key: "highLeverage" as const, label: "High Leverage" },
    { key: "humanInTheLoop" as const, label: "Human-in-the-Loop" },
    { key: "humanLed" as const, label: "Human-Led" },
  ];
  for (const { key, label } of buckets) {
    const prev = previous.aiApplicability[key];
    const curr = current.aiApplicability[key];
    if (prev.min !== curr.min || prev.max !== curr.max) {
      aiShifts.push({
        bucket: label,
        oldRange: `${prev.min}–${prev.max}%`,
        newRange: `${curr.min}–${curr.max}%`,
      });
    }
  }

  const metrics = [
    { key: "effortAddressable" as const, label: "Effort Addressable" },
    { key: "costSavingsRange" as const, label: "Cost Savings" },
    { key: "capacityUnlocked" as const, label: "Capacity Unlocked" },
  ];
  for (const { key, label } of metrics) {
    const prev = previous.automationOpportunity[key];
    const curr = current.automationOpportunity[key];
    if (prev.min !== curr.min || prev.max !== curr.max) {
      oppShifts.push({
        metric: label,
        oldRange: `${prev.min}–${prev.max}%`,
        newRange: `${curr.min}–${curr.max}%`,
      });
    }
  }

  if (aiShifts.length === 0 && oppShifts.length === 0) return null;
  return { aiApplicabilityShifts: aiShifts, opportunityShifts: oppShifts };
}

function hasAssessmentData(engagement: Engagement): boolean {
  return engagement.processAssessments.some(
    (pa) => pa.maturityRatings && Object.keys(pa.maturityRatings).length > 0
  );
}

export function HypothesisPageClient({
  engagementId,
}: HypothesisPageClientProps) {
  const router = useRouter();
  const [engagement, setEngagement] = useState<Engagement | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isRefining, setIsRefining] = useState(false);
  const [delta, setDelta] = useState<DiagnosticDelta | null>(null);
  const [showDelta, setShowDelta] = useState(true);
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    const loaded = getEngagement(engagementId);
    if (!loaded) {
      router.push("/engagements");
      return;
    }
    setEngagement(loaded);
  }, [engagementId, router]);

  // Auto-generate diagnostic on mount if not present
  useEffect(() => {
    if (!engagement || hasAutoGenerated.current) return;
    if (engagement.diagnostic) return;

    hasAutoGenerated.current = true;
    generateDiagnostic(engagement);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [engagement]);

  const stale = useMemo(
    () => (engagement ? isDiagnosticStale(engagement) : false),
    [engagement]
  );

  const generateDiagnostic = async (eng: Engagement) => {
    setIsGenerating(true);
    setDelta(null);
    try {
      const diagnostic = await generateAIDiagnostic(
        eng.clientContext,
        eng.processAssessments
      );
      const updated = {
        ...eng,
        diagnostic,
        updatedAt: new Date().toISOString(),
      };
      saveEngagement(updated);
      setEngagement(updated);
      window.dispatchEvent(new Event("engagement-updated"));
    } finally {
      setIsGenerating(false);
    }
  };

  const refineDiagnostic = async (eng: Engagement) => {
    if (!eng.diagnostic) return;
    setIsRefining(true);
    setDelta(null);
    try {
      const previousDiagnostic = eng.diagnostic;
      const refined = await generateRefinedDiagnostic(
        eng.clientContext,
        eng.processAssessments,
        previousDiagnostic
      );

      const history = [...(eng.diagnosticHistory || []), previousDiagnostic];

      const updated: Engagement = {
        ...eng,
        diagnostic: refined,
        diagnosticHistory: history,
        updatedAt: new Date().toISOString(),
      };
      saveEngagement(updated);
      setEngagement(updated);
      window.dispatchEvent(new Event("engagement-updated"));

      const computedDelta = computeDelta(previousDiagnostic, refined);
      setDelta(computedDelta);
      setShowDelta(true);
    } finally {
      setIsRefining(false);
    }
  };

  if (!engagement) {
    return (
      <div className="text-center py-12 text-muted-foreground">Loading...</div>
    );
  }

  if (isGenerating || isRefining) {
    return (
      <div className="flex flex-col items-center justify-center py-24 gap-4">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
        <div className="text-center">
          <p className="font-medium">
            {isRefining ? "Refining Opportunity Areas" : "Generating Opportunity Areas"}
          </p>
          <p className="text-sm text-muted-foreground mt-1">
            {isRefining
              ? "Recalibrating based on your assessment data..."
              : `Analyzing ${engagement.clientContext.companyName}\u2019s profile and processes...`}
          </p>
        </div>
      </div>
    );
  }

  if (!engagement.diagnostic) {
    return (
      <div className="text-center py-16">
        <p className="text-sm text-muted-foreground mb-4">
          Failed to generate opportunity areas. Please try again.
        </p>
        <Button onClick={() => generateDiagnostic(engagement)}>
          <RefreshCw className="h-4 w-4 mr-2" />
          Retry
        </Button>
      </div>
    );
  }

  const isRefined =
    engagement.diagnosticHistory && engagement.diagnosticHistory.length > 0;
  const hasAssessment = hasAssessmentData(engagement);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-sm font-semibold tracking-wider uppercase text-muted-foreground">
          {isRefined ? "Refined Opportunity Areas" : "Initial Opportunity Areas (Outside-In)"}
        </h2>
        <Button
          variant="outline"
          size="sm"
          onClick={() => generateDiagnostic(engagement)}
          disabled={isGenerating || isRefining}
        >
          <RefreshCw className="h-3.5 w-3.5 mr-1.5" />
          Regenerate
        </Button>
      </div>

      {/* Outside-in banner when no assessment data */}
      {!hasAssessment && !stale && (
        <div className="flex items-center justify-between rounded-lg border border-blue-200 bg-blue-50 px-4 py-3">
          <div className="flex items-start gap-2.5">
            <Info className="h-4 w-4 text-blue-600 mt-0.5 shrink-0" />
            <div>
              <p className="text-sm font-medium text-blue-900">
                Outside-in analysis
              </p>
              <p className="text-xs text-blue-700 mt-0.5">
                These opportunities are based on outside-in analysis of company profile and industry benchmarks. Take the process assessment to refine with internal expert knowledge.
              </p>
            </div>
          </div>
          <Link href={`/engagements/${engagementId}/assessment`}>
            <Button
              size="sm"
              variant="outline"
              className="ml-4 shrink-0 border-blue-300 text-blue-700 hover:bg-blue-100"
            >
              Take Assessment
              <ArrowRight className="h-3.5 w-3.5 ml-1.5" />
            </Button>
          </Link>
        </div>
      )}

      {/* Staleness banner — assessment data exists but diagnostic is stale */}
      {stale && (
        <div className="flex items-center justify-between rounded-lg border border-amber-200 bg-amber-50 px-4 py-3">
          <div>
            <p className="text-sm font-medium text-amber-900">
              Assessment data available
            </p>
            <p className="text-xs text-amber-700 mt-0.5">
              Assessment data available — refresh to incorporate your process-level insights into these opportunity areas.
            </p>
          </div>
          <Button
            size="sm"
            onClick={() => refineDiagnostic(engagement)}
            disabled={isRefining}
            className="ml-4 shrink-0"
          >
            <Sparkles className="h-3.5 w-3.5 mr-1.5" />
            Refresh Opportunities
          </Button>
        </div>
      )}

      {/* Delta summary after refinement */}
      {delta && (
        <div className="rounded-lg border border-blue-200 bg-blue-50 px-4 py-3">
          <button
            onClick={() => setShowDelta(!showDelta)}
            className="flex items-center justify-between w-full text-left"
          >
            <p className="text-sm font-medium text-blue-900">
              Opportunity areas updated — see what changed
            </p>
            {showDelta ? (
              <ChevronUp className="h-4 w-4 text-blue-600" />
            ) : (
              <ChevronDown className="h-4 w-4 text-blue-600" />
            )}
          </button>
          {showDelta && (
            <div className="mt-3 space-y-2">
              {delta.aiApplicabilityShifts.map((shift) => (
                <div
                  key={shift.bucket}
                  className="flex items-center gap-2 text-xs text-blue-800"
                >
                  <span className="font-medium">{shift.bucket}:</span>
                  <span className="text-blue-600 line-through">
                    {shift.oldRange}
                  </span>
                  <span className="text-blue-900 font-medium">
                    {shift.newRange}
                  </span>
                </div>
              ))}
              {delta.opportunityShifts.map((shift) => (
                <div
                  key={shift.metric}
                  className="flex items-center gap-2 text-xs text-blue-800"
                >
                  <span className="font-medium">{shift.metric}:</span>
                  <span className="text-blue-600 line-through">
                    {shift.oldRange}
                  </span>
                  <span className="text-blue-900 font-medium">
                    {shift.newRange}
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      <DiagnosticOverview
        diagnostic={engagement.diagnostic}
        companyName={engagement.clientContext.companyName}
        industry={engagement.clientContext.industry}
        companySize={engagement.clientContext.companySize}
        engagementId={engagement.id}
      />
    </div>
  );
}
